// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unwisxczcoeoshwybktg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVud2lzeGN6Y29lb3Nod3lia3RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MTE2MzEsImV4cCI6MjA1ODQ4NzYzMX0.CQWn7zkuEHAIPCNPB8nIGCaZE1hut2umQEMdRkq3IFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
