// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqcmhbliavkxsewlphbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxY21oYmxpYXZreHNld2xwaGJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MTM1MzMsImV4cCI6MjA1ODI4OTUzM30.meq1HLNgf7edr9036r_pW_bM_F1eNc4N0lgzHPvraOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);